spring:
   application:
      name: greeting-service
management:
   endpoints:
      web:
          exposure:
             include: 
                - '*'
greeting-service:
   greeting: "saddsad"
   default-value: "Mundo"